/**
 * Generate wrangler.toml for the Router Worker from nextjs-versions.json.
 * Run: bun run generate-wrangler.ts
 */
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname!, '../..');
const versionsData = JSON.parse(
  await Bun.file(resolve(ROOT, '.github/nextjs-versions.json')).text(),
);
const latestMajor = versionsData.latestMajor;
const olderVersions = Object.keys(versionsData.versions).filter(
  (v) => v !== latestMajor,
);

const bindings = [
  `[[services]]\nbinding = "LATEST"\nservice = "nextjs-docs-latest"`,
  ...olderVersions.map(
    (v) =>
      `[[services]]\nbinding = "V${v}_DOCS"\nservice = "nextjs-docs-v${v}"`,
  ),
].join('\n\n');

const config = `# Auto-generated by generate-wrangler.ts — do not edit manually
name = "nextjs-docs-router"
main = "src/index.ts"
compatibility_date = "2025-03-14"

# Service bindings to version-specific workers
${bindings}

# Custom domain
# [routes]
# pattern = "nextjs.im/*"
`;

const outPath = resolve(import.meta.dirname!, 'wrangler.toml');
await Bun.write(outPath, config);
console.log(`Generated ${outPath}`);
console.log(`  LATEST → nextjs-docs-latest`);
for (const v of olderVersions) {
  console.log(`  V${v}_DOCS → nextjs-docs-v${v}`);
}
