name: 'Check Locale Changes'
description: 'Check which enabled locales have changes and generate deployment matrix'
inputs:
  trigger-type:
    description: 'Type of trigger: "manual", "auto", or "docs-pr"'
    required: true
  manual-locales:
    description: 'Comma-separated list of locales for manual trigger (optional)'
    required: false
    default: ''
outputs:
  matrix-include:
    description: 'JSON array of locales to deploy with their config'
    value: ${{ steps.check-locales.outputs.matrix-include }}
  has-changes:
    description: 'Whether any enabled locales have changes'
    value: ${{ steps.check-locales.outputs.has-changes }}

runs:
  using: 'composite'
  steps:
    - name: Check locale changes and generate matrix
      id: check-locales
      shell: bash
      run: |
        # Use the unified Node.js script to handle everything
        node .github/scripts/check-locale-changes.js "${{ inputs.trigger-type }}" "${{ inputs.manual-locales }}" "true"
