name: 'Comment Vercel Preview'
description: 'Comment Vercel deploy preview links on a PR.'
inputs:
  inspect_url:
    description: 'Inspect URL from Vercel deploy output.'
    required: true
  preview_url:
    description: 'Preview/Production URL from Vercel deploy output.'
    required: true
  label:
    description: 'Label for the deployment (e.g., EN, ZH-HANS).'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Comment PR with Vercel Preview Links
      uses: actions/github-script@v7
      with:
        script: |
          const inspect = process.env.INSPECT_URL;
          const preview = process.env.PREVIEW_URL;
          let body = `**Vercel Deploy Preview (${process.env.LABEL})**\n\n`;
          body += `- [Inspect](${inspect}) | [Preview](${preview})`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body
          });
      env:
        INSPECT_URL: ${{ inputs.inspect_url }}
        PREVIEW_URL: ${{ inputs.preview_url }}
        LABEL: ${{ inputs.label }}
