name: 'Update Search Index'
description: 'Build docs and update Orama search index for a given locale.'
inputs:
  locale:
    description: "Locale to update (e.g., 'en' or 'zh-hans')"
    required: true
  orama_private_api_key_en:
    description: "Orama Private API Key for EN"
    required: true
  orama_private_api_key_zh_hans:
    description: "Orama Private API Key for ZH-HANS"
    required: true
runs:
  using: "composite"
  steps:
    - name: Build docs
      shell: bash
      run: pnpm build:docs
      env:
        LOCALE: "${{ inputs.locale }}"
        GEN_ORAMA_STATIC: "true"
        MDX_ASYNC: "true"
        NODE_OPTIONS: "--max-old-space-size=8192"
    - name: Update Search Index
      shell: bash
      run: pnpm run update-search-index
      env:
        LOCALE: "${{ inputs.locale }}"
        ORAMA_PRIVATE_API_KEY_EN: ${{ inputs.orama_private_api_key_en }}
        ORAMA_PRIVATE_API_KEY_ZH_HANS: ${{ inputs.orama_private_api_key_zh_hans }}
