name: "Vercel Deploy"
description: "Deploy to Vercel and output preview/inspect URLs"
inputs:
  environment:
    description: "Vercel environment (production or preview)"
    required: true
  prodFlag:
    description: "Set to --prod for production deploys, empty for preview"
    required: false
    default: ""
  vercel_project_id:
    required: true
  vercel_org_id:
    required: true
  vercel_token:
    required: true
outputs:
  inspect_url:
    description: "Vercel inspect URL"
    value: ${{ steps.vercel_deploy.outputs.inspect_url }}
  prod_url:
    description: "Vercel preview/production URL"
    value: ${{ steps.vercel_deploy.outputs.prod_url }}
runs:
  using: "composite"
  steps:
    - name: Pull Vercel Environment Information
      run: npx vercel pull --yes --environment=${{ inputs.environment }} --token=${{ inputs.vercel_token }}
      env:
        VERCEL_PROJECT_ID: ${{ inputs.vercel_project_id }}
        VERCEL_ORG_ID: ${{ inputs.vercel_org_id }}
      shell: bash
    - name: Echo Vercel Environment File
      run: |
        ls -l .vercel/.env*
        for f in .vercel/.env*; do
          echo "\n----- $f -----"
          cat "$f"
        done
      shell: bash
    - name: Build Project Artifacts
      run: npx vercel build ${{ inputs.prodFlag }} --token=${{ inputs.vercel_token }}
      env:
        VERCEL_PROJECT_ID: ${{ inputs.vercel_project_id }}
        VERCEL_ORG_ID: ${{ inputs.vercel_org_id }}
      shell: bash
    - name: Deploy Project Artifacts
      id: vercel_deploy
      run: |
        npx vercel deploy --prebuilt ${{ inputs.prodFlag }} --archive=tgz --token=${{ inputs.vercel_token }} 2>&1 | tee vercel_output.txt
        inspect_url=$(awk '/^Inspect:/ {print $2}' vercel_output.txt | head -n1)
        preview_url=$(awk '/^(Preview|Production):/ {print $2}' vercel_output.txt | head -n1)
        echo "inspect_url=$inspect_url" >> $GITHUB_OUTPUT
        echo "prod_url=$preview_url" >> $GITHUB_OUTPUT
      env:
        VERCEL_PROJECT_ID: ${{ inputs.vercel_project_id }}
        VERCEL_ORG_ID: ${{ inputs.vercel_org_id }}
      shell: bash
