name: "Vercel Build"
description: "Build project artifacts using Vercel CLI for deployment."
inputs:
  environment:
    description: "Vercel environment (production or preview)"
    required: true
  prodFlag:
    description: "Set to --prod for production deploys, empty for preview"
    required: false
    default: ""
  vercel_project_id:
    required: true
  vercel_org_id:
    required: true
  vercel_token:
    required: true
runs:
  using: "composite"
  steps:
    - name: Pull Vercel Environment Information
      run: npx vercel pull --yes --environment=${{ inputs.environment }} --token=${{ inputs.vercel_token }}
      env:
        VERCEL_PROJECT_ID: ${{ inputs.vercel_project_id }}
        VERCEL_ORG_ID: ${{ inputs.vercel_org_id }}
      shell: bash
    - name: Echo Vercel Environment File
      run: |
        ls -l .vercel/.env*
        for f in .vercel/.env*; do
          echo "\n----- $f -----"
          cat "$f"
        done
      shell: bash
    - name: Build Project Artifacts
      run: npx vercel build ${{ inputs.prodFlag }} --token=${{ inputs.vercel_token }}
      env:
        VERCEL_PROJECT_ID: ${{ inputs.vercel_project_id }}
        VERCEL_ORG_ID: ${{ inputs.vercel_org_id }}
      shell: bash
