name: Build Translate Translate Package
description: Action that builds the translate package and makes it executable
runs:
  using: composite
  steps:
    - name: Build packages
      shell: bash
      run: pnpm build:packages
    
    - name: Link binaries and make executable
      shell: bash
      run: |
        chmod +x ./packages/translate/dist/index.js
        echo "Verifying translate-docs binary exists"
        ls -la ./packages/translate/dist/index.js || true
