name: Vercel Preview Deployment

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy-en:
    uses: ./.github/workflows/vercel-deploy.yml
    with:
      environment: preview
      prodFlag: ''
    secrets:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_EN_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  deploy-zh-hans:
    uses: ./.github/workflows/vercel-deploy.yml
    with:
      environment: preview
      prodFlag: ''
    secrets:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ZH_HANS_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
