name: Pre-release

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - labeled
      - synchronize

permissions:
  pull-requests: write
  issues: write

jobs:
  deploy:
    if: contains(github.event.pull_request.labels.*.name, 'prerelease')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Deploy EN
            locale: EN
            secret_project_id: VERCEL_PROJECT_EN_ID
          - name: Deploy ZH-HANS
            locale: ZH-HANS
            secret_project_id: VERCEL_PROJECT_ZH_HANS_ID
    name: ${{ matrix.name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Tools
        uses: ./.github/actions/setup
      - name: Deploy to Vercel (${{ matrix.locale }})
        id: deploy
        uses: ./.github/actions/vercel-deploy
        with:
          environment: preview
          prodFlag: ""
          vercel_project_id: ${{ secrets[matrix.secret_project_id] }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
      - name: Comment PR with Vercel Preview Links (${{ matrix.locale }})
        uses: ./.github/actions/comment-vercel-preview
        with:
          inspect_url: ${{ steps.deploy.outputs.inspect_url }}
          preview_url: ${{ steps.deploy.outputs.prod_url }}
          label: ${{ matrix.locale }}
