name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-and-update-index:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - locale: en
            secret_project_id: VERCEL_PROJECT_EN_ID
          - locale: zh-hans
            secret_project_id: VERCEL_PROJECT_ZH_HANS_ID
          - locale: zh-hant
            secret_project_id: VERCEL_PROJECT_ZH_HANT_ID
    name: Deploy ${{ matrix.locale }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Tools
        uses: ./.github/actions/setup
      - name: Deploy to Vercel (${{ matrix.locale }})
        id: deploy
        uses: ./.github/actions/vercel-deploy
        with:
          environment: production
          prodFlag: --prod
          vercel_project_id: ${{ secrets[matrix.secret_project_id] }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
      - name: Copy .vercel/.env.production.local
        shell: bash
        run: |
          cp .vercel/.env.production.local apps/docs/.env
      - name: Update Search Index
        shell: bash
        run: pnpm run docs:update-search-index
