name: E2E Tests

on:
  workflow_call:
    inputs:
      matrix-include:
        description: 'Matrix configuration for locales'
        required: true
        type: string
      shard-total:
        description: 'Total number of shards'
        required: false
        type: number
        default: 1

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      test-matrix: ${{ steps.generate-matrix.outputs.test-matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Setup Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: .nvmrc
      
      - name: Generate test matrix
        id: generate-matrix
        run: |
          # Use the Node.js script to generate the matrix
          output=$(node .github/scripts/generate-e2e-matrix.js '${{ inputs.matrix-include }}' ${{ inputs.shard-total }})
          echo "$output" >> $GITHUB_OUTPUT
          echo "Generated matrix: $output"

  test:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.test-matrix) }}
    name: Test ${{ matrix.locale }}${{ inputs.shard-total > 1 && format(' (Shard {0}/{1})', matrix.shard, inputs.shard-total) || '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - uses: ./.github/actions/setup
      
      - uses: ./.github/actions/vercel-pull
        with:
          environment: production
          prodFlag: --prod
          vercel_project_id: ${{ secrets[matrix.secret_project_id] }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
      
      - uses: ./.github/actions/vercel-build
        with:
          environment: production
          prodFlag: --prod
          vercel_project_id: ${{ secrets[matrix.secret_project_id] }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
      
      - name: Install E2E Dependencies
        run: |
          pnpm --filter @next-i18n/docs playwright:install
    
      - name: Run E2E Tests
        env:
          LOCALE: ${{ matrix.locale }}
        run: |
          echo "Running tests for ${{ matrix.locale }} (Shard ${{ matrix.shard }}/${{ inputs.shard-total }})"
          pnpm --filter @next-i18n/docs test:e2e --shard ${{ matrix.shard }}/${{ inputs.shard-total }}
