name: Update Search Index

on:
  workflow_call:
    inputs:
      locale:
        description: "Locale to update (e.g., 'en' or 'zh-hans')"
        required: true
        type: string
    secrets:
      ORAMA_PRIVATE_API_KEY_EN:
        required: true
      ORAMA_PRIVATE_API_KEY_ZH_HANS:
        required: true

jobs:
  update-search-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Tools
        uses: ./.github/actions/setup

      - name: Build docs
        shell: bash
        run: pnpm build:docs
        env:
          LOCALE: "${{ inputs.locale }}"
          GEN_ORAMA_STATIC: "true"
          MDX_ASYNC: "true"
          NODE_OPTIONS: "--max-old-space-size=8192"

      - name: Update Search Index
        shell: bash
        run: pnpm run update-search-index
        env:
          LOCALE: "${{ inputs.locale }}"
          ORAMA_PRIVATE_API_KEY_EN: ${{ secrets.ORAMA_PRIVATE_API_KEY_EN }}
          ORAMA_PRIVATE_API_KEY_ZH_HANS: ${{ secrets.ORAMA_PRIVATE_API_KEY_ZH_HANS }}
