name: Update Docs CI

on:
  push:
    branches:
      - docs/update-translations
      - docs/sync-nextjs-documentation

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository first to access local actions
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Tools
        # After pnpm install, apps/docs will execute postinstall: fumadocs-mdx
        # Which will generated MDX types (check if the docs frontmatter is correct)
        uses: ./.github/actions/setup
