name: Update Docs CI

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - dev

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix-include: ${{ steps.check-locales.outputs.matrix-include }}
      has-changes: ${{ steps.check-locales.outputs.has-changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Check locale changes
        id: check-locales
        uses: ./.github/actions/check-locale-changes
        with:
          trigger-type: docs-pr
  test:
    needs: check-changes
    if: needs.check-changes.outputs.has-changes == 'true' && startsWith(github.head_ref, 'docs/')
    uses: ./.github/workflows/test-e2e.yml
    with:
      matrix-include: ${{ needs.check-changes.outputs.matrix-include }}
      shard-total: 5
    secrets: inherit

  deploy-and-update-index:
    needs: [check-changes, test]
    if: needs.check-changes.outputs.has-changes == 'true' && startsWith(github.head_ref, 'docs/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.check-changes.outputs.matrix-include) }}
    name: Build ${{ matrix.locale }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/vercel-pull
        with:
          environment: production
          prodFlag: --prod
          vercel_project_id: ${{ secrets[matrix.secret_project_id] }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
      - uses: ./.github/actions/vercel-build
        with:
          environment: production
          prodFlag: --prod
          vercel_project_id: ${{ secrets[matrix.secret_project_id] }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
