name: Vercel Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: "Vercel environment (production or preview)"
        required: true
        type: string
      prodFlag:
        description: "Set to --prod for production deploys, empty for preview"
        required: false
        type: string
        default: ""
    secrets:
      VERCEL_PROJECT_ID:
        required: true
      VERCEL_ORG_ID:
        required: true
      VERCEL_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Setup Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: .nvmrc

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{ inputs.environment }} --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

      - name: Build Project Artifacts
        run: vercel build ${{ inputs.prodFlag }} --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt ${{ inputs.prodFlag }} --archive=tgz --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
